FROM node:20-alpine

WORKDIR /app

COPY Renyou-Shop-Project--main--v2/frontend/package*.json ./

RUN npm install

COPY Renyou-Shop-Project--main--v2/frontend/ .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]