export const COUNTRIES = {
  'Algeria':{'flag':'🇩🇿','code':'DZ'},'Angola':{'flag':'🇦🇴','code':'AO'},'Benin':{'flag':'🇧🇯','code':'BJ'},'Botswana':{'flag':'🇧🇼','code':'BW'},'Burkina Faso':{'flag':'🇧🇫','code':'BF'},'Cameroon':{'flag':'🇨🇲','code':'CM'},'Cape Verde':{'flag':'🇨🇻','code':'CV'},'Egypt':{'flag':'🇪🇬','code':'EG'},'Ethiopia':{'flag':'🇪🇹','code':'ET'},'Ghana':{'flag':'🇬🇭','code':'GH'},'Ivory Coast':{'flag':'🇨🇮','code':'CI'},'Kenya':{'flag':'🇰🇪','code':'KE'},'Libya':{'flag':'🇱🇾','code':'LY'},'Madagascar':{'flag':'🇲🇬','code':'MG'},'Mali':{'flag':'🇲🇱','code':'ML'},'Mauritania':{'flag':'🇲🇷','code':'MR'},'Morocco':{'flag':'🇲🇦','code':'MA'},'Mozambique':{'flag':'🇲🇿','code':'MZ'},'Namibia':{'flag':'🇳🇦','code':'NA'},'Niger':{'flag':'🇳🇪','code':'NE'},'Nigeria':{'flag':'🇳🇬','code':'NG'},'Rwanda':{'flag':'🇷🇼','code':'RW'},'Senegal':{'flag':'🇸🇳','code':'SN'},'Somalia':{'flag':'🇸🇴','code':'SO'},'South Africa':{'flag':'🇿🇦','code':'ZA'},'Sudan':{'flag':'🇸🇩','code':'SD'},'Tanzania':{'flag':'🇹🇿','code':'TZ'},'Togo':{'flag':'🇹🇬','code':'TG'},'Tunisia':{'flag':'🇹🇳','code':'TN'},'Uganda':{'flag':'🇺🇬','code':'UG'},'Zimbabwe':{'flag':'🇿🇼','code':'ZW'},
  'Argentina':{'flag':'🇦🇷','code':'AR'},'Bolivia':{'flag':'🇧🇴','code':'BO'},'Brazil':{'flag':'🇧🇷','code':'BR'},'Canada':{'flag':'🇨🇦','code':'CA'},'Chile':{'flag':'🇨🇱','code':'CL'},'Colombia':{'flag':'🇨🇴','code':'CO'},'Cuba':{'flag':'🇨🇺','code':'CU'},'Ecuador':{'flag':'🇪🇨','code':'EC'},'Guatemala':{'flag':'🇬🇹','code':'GT'},'Haiti':{'flag':'🇭🇹','code':'HT'},'Honduras':{'flag':'🇭🇳','code':'HN'},'Jamaica':{'flag':'🇯🇲','code':'JM'},'Mexico':{'flag':'🇲🇽','code':'MX'},'Nicaragua':{'flag':'🇳🇮','code':'NI'},'Panama':{'flag':'🇵🇦','code':'PA'},'Paraguay':{'flag':'🇵🇾','code':'PY'},'Peru':{'flag':'🇵🇪','code':'PE'},'Puerto Rico':{'flag':'🇵🇷','code':'PR'},'Uruguay':{'flag':'🇺🇾','code':'UY'},'USA':{'flag':'🇺🇸','code':'US'},'Venezuela':{'flag':'🇻🇪','code':'VE'},
  'Afghanistan':{'flag':'🇦🇫','code':'AF'},'Armenia':{'flag':'🇦🇲','code':'AM'},'Azerbaijan':{'flag':'🇦🇿','code':'AZ'},'Bahrain':{'flag':'🇧🇭','code':'BH'},'Bangladesh':{'flag':'🇧🇩','code':'BD'},'Cambodia':{'flag':'🇰🇭','code':'KH'},'China':{'flag':'🇨🇳','code':'CN'},'Georgia':{'flag':'🇬🇪','code':'GE'},'Hong Kong':{'flag':'🇭🇰','code':'HK'},'India':{'flag':'🇮🇳','code':'IN'},'Indonesia':{'flag':'🇮🇩','code':'ID'},'Iran':{'flag':'🇮🇷','code':'IR'},'Iraq':{'flag':'🇮🇶','code':'IQ'},'Israel':{'flag':'🇮🇱','code':'IL'},'Japan':{'flag':'🇯🇵','code':'JP'},'Jordan':{'flag':'🇯🇴','code':'JO'},'Kazakhstan':{'flag':'🇰🇿','code':'KZ'},'Kuwait':{'flag':'🇰🇼','code':'KW'},'Lebanon':{'flag':'🇱🇧','code':'LB'},'Malaysia':{'flag':'🇲🇾','code':'MY'},'Mongolia':{'flag':'🇲🇳','code':'MN'},'Myanmar':{'flag':'🇲🇲','code':'MM'},'Nepal':{'flag':'🇳🇵','code':'NP'},'Oman':{'flag':'🇴🇲','code':'OM'},'Pakistan':{'flag':'🇵🇰','code':'PK'},'Palestine':{'flag':'🇵🇸','code':'PS'},'Philippines':{'flag':'🇵🇭','code':'PH'},'Qatar':{'flag':'🇶🇦','code':'QA'},'Saudi Arabia':{'flag':'🇸🇦','code':'SA'},'Singapore':{'flag':'🇸🇬','code':'SG'},'South Korea':{'flag':'🇰🇷','code':'KR'},'Sri Lanka':{'flag':'🇱🇰','code':'LK'},'Syria':{'flag':'🇸🇾','code':'SY'},'Taiwan':{'flag':'🇹🇼','code':'TW'},'Thailand':{'flag':'🇹🇭','code':'TH'},'Turkey':{'flag':'🇹🇷','code':'TR'},'UAE':{'flag':'🇦🇪','code':'AE'},'Uzbekistan':{'flag':'🇺🇿','code':'UZ'},'Vietnam':{'flag':'🇻🇳','code':'VN'},'Yemen':{'flag':'🇾🇪','code':'YE'},
  'Albania':{'flag':'🇦🇱','code':'AL'},'Austria':{'flag':'🇦🇹','code':'AT'},'Belarus':{'flag':'🇧🇾','code':'BY'},'Belgium':{'flag':'🇧🇪','code':'BE'},'Bosnia':{'flag':'🇧🇦','code':'BA'},'Bulgaria':{'flag':'🇧🇬','code':'BG'},'Croatia':{'flag':'🇭🇷','code':'HR'},'Cyprus':{'flag':'🇨🇾','code':'CY'},'Czech Republic':{'flag':'🇨🇿','code':'CZ'},'Denmark':{'flag':'🇩🇰','code':'DK'},'Estonia':{'flag':'🇪🇪','code':'EE'},'Finland':{'flag':'🇫🇮','code':'FI'},'France':{'flag':'🇫🇷','code':'FR'},'Germany':{'flag':'🇩🇪','code':'DE'},'Greece':{'flag':'🇬🇷','code':'GR'},'Hungary':{'flag':'🇭🇺','code':'HU'},'Iceland':{'flag':'🇮🇸','code':'IS'},'Ireland':{'flag':'🇮🇪','code':'IE'},'Italy':{'flag':'🇮🇹','code':'IT'},'Latvia':{'flag':'🇱🇻','code':'LV'},'Lithuania':{'flag':'🇱🇹','code':'LT'},'Luxembourg':{'flag':'🇱🇺','code':'LU'},'Malta':{'flag':'🇲🇹','code':'MT'},'Moldova':{'flag':'🇲🇩','code':'MD'},'Monaco':{'flag':'🇲🇨','code':'MC'},'Montenegro':{'flag':'🇲🇪','code':'ME'},'Netherlands':{'flag':'🇳🇱','code':'NL'},'Norway':{'flag':'🇳🇴','code':'NO'},'Poland':{'flag':'🇵🇱','code':'PL'},'Portugal':{'flag':'🇵🇹','code':'PT'},'Romania':{'flag':'🇷🇴','code':'RO'},'Russia':{'flag':'🇷🇺','code':'RU'},'Serbia':{'flag':'🇷🇸','code':'RS'},'Slovakia':{'flag':'🇸🇰','code':'SK'},'Slovenia':{'flag':'🇸🇮','code':'SI'},'Spain':{'flag':'🇪🇸','code':'ES'},'Sweden':{'flag':'🇸🇪','code':'SE'},'Switzerland':{'flag':'🇨🇭','code':'CH'},'Ukraine':{'flag':'🇺🇦','code':'UA'},'UK':{'flag':'🇬🇧','code':'GB'},
  'Australia':{'flag':'🇦🇺','code':'AU'},'Fiji':{'flag':'🇫🇯','code':'FJ'},'New Zealand':{'flag':'🇳🇿','code':'NZ'},'Papua New Guinea':{'flag':'🇵🇬','code':'PG'},
};
export const COUNTRY_NAMES = Object.keys(COUNTRIES).sort();
export function getFlag(country) { return COUNTRIES[country]?.flag || '🌍'; }
export function getCode(country) { return COUNTRIES[country]?.code || '??'; }
